"""create challenges and questions tables

Revision ID: 3e3411583efd
Revises: 19ce0e91501e
Create Date: 2026-07-19 03:08:01.795809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e3411583efd'
down_revision: Union[str, Sequence[str], None] = '19ce0e91501e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('passing_score', sa.Integer(), server_default='70', nullable=False),
    sa.Column('xp_reward', sa.Integer(), server_default='100', nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='challenge_status'), server_default='draft', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_challenges_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges'))
    )
    op.create_index(op.f('ix_challenges_is_active'), 'challenges', ['is_active'], unique=False)
    op.create_index(op.f('ix_challenges_lesson_id'), 'challenges', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_challenges_status'), 'challenges', ['status'], unique=False)
    op.create_table('questions',
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('multiple_choice', 'true_false', name='question_type'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_questions_challenge_id_challenges'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('challenge_id', 'position', name='uq_questions_challenge_position')
    )
    op.create_index(op.f('ix_questions_challenge_id'), 'questions', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_questions_is_active'), 'questions', ['is_active'], unique=False)
    op.create_index(op.f('ix_questions_question_type'), 'questions', ['question_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_question_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_is_active'), table_name='questions')
    op.drop_index(op.f('ix_questions_challenge_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_challenges_status'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_lesson_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_is_active'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
